### PR TITLE
replace requireText with require and replace .ms with .html

### PR DESCRIPTION
**Pull request by bjfletcher**
1. `requireText` is replaced with `require` where the build system is allowed to decide on how to load the module based on the ID's pattern - even doing the same behaviour as `requireText`.  E.g., with webpack, that'd be the raw loader.
2. The extension `.ms` is replace with `.html` to be consistent with the rest of the FT code. We use `.html` even if it's a template.

_Note_: I'm currently testing this, please don't merge for the time being.

### CODE REVIEW

**Comment by bjfletcher** [comment]
Hi again,

I've just done some testing and this is working great.

Please merge. I suggest releasing this as v3:

`git tag v3.0.0`

**Comment by matthew-andrews** [comment]
@bjfletcher do you think it's worth explaining a little bit of background about why these pull requests came about to help roland + others in the morning ☺️

**Comment by bjfletcher** [comment]
@matthew-andrews Yes :/ I'll try and get hold of Roland on Slack in the morning.

**Comment by matthew-andrews** [comment]
just be aware they work a few hours earlier than us from romania so they're likely to see this long before you grab them :-)

**Comment by roland-vachter** [comment]
Hey Ben,
If this is compatible with origami build tools, then that's fine. We already have a v3 branch, so I will merge it manually onto that branch.

**Pull request closed without merging**
