### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-comment-ui bundle size difference from 5.0.2 to 1a6b71bcf808121fff527c837fdc643cefb6f2c7
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-comment-ui bundle size difference from 5.0.2 to ff7bf9865f9140cd93ec6060d8cb1c1094e9beda
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-comment-ui bundle size difference from 5.0.2 to 5fce827241804306422e1282965f5ef3058d6291
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-comment-ui bundle size difference from 5.0.2 to af2fc8fac1aa64705bf747f172d32e2b67ed7ca9
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-comment-ui bundle size difference from 5.0.2 to b8682937d3ed683d5aa72ff6d3d3fc375114485e
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-comment-ui bundle size difference from 5.0.2 to cf1dcb0afc3f1fb1fc01b59aa974ca8e552cc0fb
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Review by chee — APPROVED** [review]

**Pull request merged**
