### PR TITLE
Bump o-icons

### PR DESCRIPTION
**Pull request by remybach**

### CODE REVIEW

**Comment by notlee** [comment]
Hey @remybach this is a breaking change, is there anything else you would like to add to a breaking?

**Comment by JakeChampion** [comment]
An alternative to this is to use the version argument in the o-icons mixin, then you can have a ranged dependency on o-icons v4 - v5. That would not be a breaking change :-)

**Comment by remybach** [comment]
@notlee / @JakeChampion: I've had a search for [all the icons listed here](https://github.com/Financial-Times/fticons), and there was only the one I found that needed changing. Was there anything else I should be looking for specifically?

**Comment by notlee** [comment]
Ah of course :facepalm: thanks @JakeChampion!

@remybach  to avoid a breaking change we can support either v4 or v5 of `o-icons`. To do that we need to increase the semver range ` "o-icons": ">=4.0.0 <6"` and pass the version of the icon set we want to `oIconsGetIcon`. 

That's because v4 of `o-icons` defaults to our old icon set `$iconset-version: 0`:
https://github.com/Financial-Times/o-icons/blob/v4.4.6/scss/_mixins.scss#L16
And v5 of `o-icons` defaults to our new icon set `$iconset-version: 1`:
https://github.com/Financial-Times/o-icons/blob/master/scss/_mixins.scss#L16

Here's an example where I do this for o-banner.
https://github.com/Financial-Times/o-banner/pull/35/files

Let me know if you have any questions or would rather chat in person!

**Comment by remybach** [comment]
@notlee Ah, the link to that PR was super handy. Does it look right now @notlee?

**Comment by notlee** [comment]
Looks good @remybach, there's just one other use that I see which needs to specify the icon set version https://github.com/Financial-Times/o-comment-ui/blob/cf474466e781c81e3c68f3f1ef749399492683f6/src/stylesheets/commentingSettingsLink.scss#L14

**Comment by remybach** [comment]
Doh! Good catch @notlee... should be good to go now.

**Review by notlee — APPROVED** [review]

**Pull request merged**
